name: coconut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - transformers==4.41.2
      - datasets
      - accelerate
      - scikit-learn
      - tqdm
      - matplotlib
      - numpy<2
      - sentencepiece
      - einops 
      - pandas 
      - seaborn 
      - jupyter

# install pytorch separately from other packages
# pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu128
