name: coconut
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - transformers
      - datasets
      - accelerate
      - scikit-learn
      - numpy
      - pandas
      - tqdm
      - matplotlib
      - seaborn
      - einops

# install pytorch after activation
# conda activate coconut
# pip install torch==2.2.2+cu121 torchvision==0.17.2+cu121 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu121